Accept all result dirs as input param

diff --git a/get-res b/get-res
--- a/get-res
+++ b/get-res
@@ -8,9 +8,16 @@ cd $CMB_HOME
 
 res_idx=$1
 
+if [[ $res_idx == "all" ]]; then
+  for i in {1..4}; do echo "get-res $i"; $CMB_HOME/get-res $i; done
+  exit 0
+fi
+
 site=rennes
 res_dir=res.$res_idx
 
 rsync -avz --exclude latest $site.g5k:$res_dir $CMB_HOME
+echo "Errors:"; egrep -r "\[error\]" $res_dir/*/srv-* || true
 
 $CMB_HOME/proc-res $res_dir
+$CMB_HOME/csv.rb $res_dir
